### ISSUE TITLE
"Allow ligatures" checkbox doesn't seem to work

### ISSUE THREAD

**Issue by osa1** [virxkane/freetype_textdraw#1]
It seems like ligatures are always enabled. In the screenshot below "allow ligatures" is disabled, but the text is still rendered with ligatures.

![Screenshot_2022-01-20_23-23-11](https://user-images.githubusercontent.com/448274/150416267-703974ba-7a66-4457-9173-f483cffa6136.png)

**Comment by virxkane** [comment]
To disable such ligatures we must disable 'calt' HarfBuzz feature. See https://en.wikipedia.org/wiki/List_of_typographic_features
Fixed in 75ef0820dab02d35c1ecef84371b80b392bcf3f2

**Comment by virxkane** [comment]
![Screenshot_20220617_111419](https://user-images.githubusercontent.com/36960933/174246111-20395ba1-30d2-4fbc-920d-6cfd13dd6d4a.png)
